auths/urls.py
from django.conf.urls import url
from .views import register,user_login
from django.urls import path,include
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from auths import views


app_name = "auths"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('settings/',views.user_settings,name = "settings"),
    path('user_profile/<str:username>/about/',views.user_about, name="about"),
    path('user_profile/<str:username>/',views.user_profile, name="user_profile"),
    path('password_change/',views.user_password_change,name ="password_change"),

]

blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib import admin
from django.utils.text import slugify

app_name = "posts"

urlpatterns = [
    path('/posts',views.posts,name = "posts"),
    path('',views.posts_list, name = "list"),
    path('update/<slug:slug>',views.post_update, name = "update"),
    path('create/',views.post_create, name = "create"),
    path('delete/<slug:slug>', views.post_delete, name = "delete"),
    path('krallar/<slug:slug>',views.krallar, name = "krallar"),
    path('detail/<slug:slug>',views.detail, name = "detail"),
    path('add_comment/<slug:slug>',views.add_comment, name = "add_comment"),
    path('get_child_comment_form/',views.get_child_form, name = "get_child_comment_form"),
    path('new_add_comment/<int:pk>/<str:model_type>',views.new_add_comment, name = "new_add_comment"),
    path('post_favorite_users/<slug:slug>',views.post_list_favorite_user, name = "post_list_favorite_user"),
    path('add_remove_favorite/<slug:slug>',views.add_or_remove_favorite, name = "add_remove_favorite"),


]

django_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include("blog.urls")),
    path('iletisim/',views.iletisim,name ="iletisim"),
    path('',views.anasayfa,name ="iletisim"),
    path('deneme/',views.deneme,name ="deneme"),
    path('deneme/ajax/',views.deneme_ajax,name ="deneme_ajax"),
    path('deneme/ajax_2/',views.deneme_ajax_2,name ="deneme_ajax_2"),
    path('auths/',include("auths.urls")),
    path('following/',include("following.urls")),
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.shortcuts import reverse
from unidecode import unidecode
from django.template.defaultfilters import slugify,safe
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from uuid import uuid4
import os
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User



def upload_to(instance,filename):
    uzanti = filename.split('.')[-1]
    new_name = "%s.%s" %(str(uuid4()), uzanti)
    unique_id = instance.unique_id
    return os.path.join('blog', unique_id, new_name)

class Kategori(models.Model):
    isim = models.CharField(max_length=10,verbose_name="Kategori İsim")

    class Meta:
        verbose_name_plural = "Kategoriler"

    def __str__(self):
        return self.isim


class Blog(models.Model):

    YAYIN_TASLAK = ((None,"Lutfen Birini Seçiniz"),("yayin","YAYIN"),("taslak","TASLAK"))

    user = models.ForeignKey(User, default = 1, null = True, verbose_name = "User",related_name = "blog", on_delete = models.PROTECT)

    title = models.CharField(max_length=100,blank = False, null = True, verbose_name="başlık",help_text="Başlık bilgisi burada girilir.")

    content = RichTextField(null = True,blank = False,max_length = 5000, verbose_name = "içerik" )
    slug = models.SlugField(null=True, unique=True, editable = False)
    image = models.ImageField(default = 'Default/hqdefault.jpg',upload_to = upload_to , blank = True,verbose_name = "Resim",null = True,help_text = "Kapak Fotoğrafı yükleyiniz.")

    yayin_taslak = models.CharField(choices = YAYIN_TASLAK, max_length = 6,null = True, blank = False)
    unique_id = models.CharField(max_length = 100, editable = True, null = True)
    kategoriler = models.ManyToManyField(to=Kategori, related_name="blog")
    created_date = models.DateTimeField(auto_now_add = True, auto_now = False)


    class Meta:
        verbose_name_plural = "Gönderiler"
        ordering = ['-created_date']
    def __str__(self):
        return "%s %s" % (self.title,self.user)

    def get_added_favorite_user(self):
        return self.favorite_blog.values_list('user__username', flat = True)

    def get_added_favorite_user_as_object(self):
        data_list = []
        qs = self.favorite_blog.all()
        for obj in qs:
            data_list.append(obj.user)
        return data_list

    def get_comment_count(self):
        yorum_sayisi = self.comment.count()
        if yorum_sayisi > 0:
            return yorum_sayisi
        return "Henüz Yorum Yok"

    def get_favorite_count(self):
        favori_sayısı = self.favorite_blog.count()
        return favori_sayısı

    @classmethod
    def get_taslak_or_yayin(cls,taslak_yayin):
        return cls.objects.filter(yayin_taslak = taslak_yayin)


    def get_yayin_taslak_html(self):
        if self.yayin_taslak == "taslak":
            return safe('<span class = "label label-{1}">{0}</span>'.format(self.get_yayin_taslak_display(),'danger'))
        return safe ('<span class = "label label-{1}">{0}</span>'.format(self.get_yayin_taslak_display(),"primary"))

    def get_absolute_url(self):
        return reverse('posts:detail',kwargs={"slug":self.slug})

    def get_image(self):
        if self.image:
            return self.image.url
        else:
            return "/media/Default/hqdefault.jpg"

    def get_unique_slug(self):
        sayi = 0
        slug = slugify(unidecode(self.title))
        new_slug =  slug
        while Blog.objects.filter(slug = new_slug).exists():
            sayi += 1
            new_slug = "%s-%s" % (slug,sayi)


        slug = new_slug
        return slug


    def save(self, *args,**kwargs):
        if self.id is None:
            new_unique_id = str(uuid4())
            self.unique_id = new_unique_id
            self.slug = self.get_unique_slug()
        else:
            blog = Blog.objects.get(slug = self.slug)
            if blog.title != self.title:
                self.slug = self.get_unique_slug()
        super(Blog, self).save(*args,**kwargs)

    def get_blog_comment(self):
        #gönderiye ait bütün yorumları bana veren fonksiyon.
        return self.comment.all()

    def get_blog_comment_count(self):
        return len(self.get_blog_new_comment())

    def get_blog_new_comment(self):
        content_type = ContentType.objects.get_for_model(self)
        object_id = self.id
        all_comment = NewComment.objects.filter(content_type = content_type, object_id = object_id)
        return all_comment




class Comment(models.Model):
    user = models.ForeignKey(User,null = True, default = 1, related_name = 'comment', on_delete = models.PROTECT)
    blog = models.ForeignKey(Blog, null = True, on_delete = models.PROTECT,related_name = "comment")
    #comment = models.ForeignKey(to = 'self', null = True, )
    comment_date = models.DateTimeField(auto_now_add = True, null = True)
    icerik = models.TextField(verbose_name = 'Yorum', max_length = 1000, blank = False, null = True)

    class Meta:
        verbose_name_plural = 'Yorumlar'


    def __str__(self):
        return "%s %s" % (self.user, self.blog)

    def get_screen_name(self):
        if self.user.first_name :
            return "%s " % (self.user.get_full_name())
        else:
            return self.user.username

class NewComment(models.Model):
    user = models.ForeignKey(User, null=True, default=1, related_name='+', on_delete=models.PROTECT)
    is_parent = models.BooleanField(default = False)

    content_type = models.ForeignKey(to = ContentType, null = True, on_delete = models.PROTECT)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type','object_id')

    comment_date = models.DateTimeField(auto_now_add=True, null=True)
    icerik = models.TextField(verbose_name='Yorum', max_length=1000, blank=False, null=True)

    def __str__(self):
        username = self.user.username
        text = "{0}  {1}".format(username, self.content_type.model)
        return  text

    class Meta:
        verbose_name_plural = "İç içe yorum sistemi"

    @classmethod
    def add_comment(cls,nesne,model_type,user,icerik):
        content_type = ContentType.objects.get_for_model(nesne.__class__)
        cls.objects.create(user = user, icerik = icerik,content_type = content_type, object_id = nesne.pk)
        if model_type == 'comment':
            nesne.is_parent = True
            nesne.save()

    def get_child_comment(self):
        if self.is_parent:
            content_type = ContentType.objects.get_for_model(self.__class__)
            all_child_comment = NewComment.objects.filter(content_type = content_type, object_id = self.pk)
            return all_child_comment
        return None

class FavoriteBlog(models.Model):
    user = models.ForeignKey(User, null = True, default = 1, related_name = 'favorite_blog', on_delete = models.PROTECT)
    blog = models.ForeignKey(Blog, null = True, related_name ='favorite_blog', on_delete = models.PROTECT)

    def __str__(self):
        return "%s %s" % (self.user, self.blog)

    class Meta:
        verbose_name_plural = "Favorilere Eklenen Gönderiler"

blog/forms.py
from django import forms
from .models import Blog,Comment

banned_email_list = ["ahmet@gmail.com","deneme@carpeu.com","ramosvaldo9@gmail.com"]

class Iletisim_Form(forms.Form):
    isim = forms.CharField(widget=forms.TextInput(attrs = {"class":"form-control"}),max_length=50,label="İsim",required=False)
    soyisim = forms.CharField(max_length=50,label="Soyisim",required=False)
    email = forms.EmailField(max_length=60,label="Email",required=True)
    email2 = forms.EmailField(max_length=50,label="Email Kontrol",required=True)
    icerik = forms.CharField(max_length=1000,label="İçerik")

    def __init__(self,*args,**kwargs):
        super(Iletisim_Form,self,).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class" : "form-control"}
        self.fields["icerik"].widget = forms.Textarea(attrs = {"class" :"form-control"}),
        #self.fields["icerik"] = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control"}))

    def clean_isim(self):
        isim = self.cleaned_data.get("isim")
        if isim == "ahmet":
            raise forms.ValidationError("lütfen ahmet dışında bir kullanıcı giriş yapsın")
        return isim

    def clean_email(self):
        email = self.cleaned_data.get("email")
        isim = self.cleaned_data.get("isim")
        if email in banned_email_list:
            raise forms.ValidationError("lütfen ban yememiş bir mail adresiyle devam ediniz.")
        return email

    def clean(self):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")

        if email != email2:
            self.add_error("email","Emailler eşleşmedi")
            self.add_error("email2","Emailler eşleşmedi")
            #raise forms.ValidationError("Emailler eşleşmedi.")


class Blog_Form(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ["title","image","content","yayin_taslak","kategoriler"]

    def __init__(self,*args,**kwargs):
        super(Blog_Form, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class" : "form-control"}
        self.fields["content"].widget.attrs["rows"] = 10
        #self.fields["content"].widget.attrs = {"rows":10, "class": "form-control"}

    def clean_content(self):
        content = self.cleaned_data.get("content")
        if len(content) < 100:
            uzunluk = len(content)
            msg = "Lütfen en az 250 karakter giriniz. Girilen karakter sayısı (%s)" %(uzunluk)
            raise forms.ValidationError(msg)
        return content

class PostSorguForm(forms.Form):
    YAYIN_TASLAK = (("all","HEPSİ"),("yayin","YAYIN"),("taslak","TASLAK"))

    search = forms.CharField(required = False, max_length = 500,widget = forms.TextInput(attrs ={'placeholder':'Bir şeyler arayınız','class':'form-control'}))
    taslak_yayin = forms.ChoiceField(label = '',widget = forms.Select(attrs = {'class':'form-control'}),choices = YAYIN_TASLAK,required = False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["icerik"]

    def __init__(self,*args,**kwargs):
        super(CommentForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {'class': "form-control"}

templates/blog/anasayfa.html
{% include 'blog/post_list.html' %}

templates/blog/post_create.html
{% extends "base.html" %}

{% block title %}
Post Create

{% endblock title %}

{% block ust_icerik %}
{% endblock %}

{% block icerik %}
<div class="row" >
    <div class="col-lg-6 col-lg-offset-3">
        <h1 class="page-header">Post Create</h1>
<form action="{% url 'posts:create' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% include 'blog/include/form-include.html' %}

    <div class="form-group">
        <div class="row">
            <div class="col-lg-12">
    <input type="submit" value="Kaydet" class="btn pull-right btn-sm btn-success">
    </div>
        </div>
        </div>
</form>
    </div>
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block ust_icerik %}
    <script type="text/javascript">
        $(document).ready(function (){
            var $window = $(this);
            var $blog_comment_list = $window.find("#blog_comment_list")
            $window.on('submit','.comment_form',function(e){
                e.preventDefault();
                var $this = $(this);
                var $method = $this.attr('method');
                var $data = $this.serialize();
                var $url = $this.attr('action');

                    $.ajax({
                    url: $url,
                    type:$method,
                    dataType:'json',
                    data:$data,
                    success:function(data){
                        $blog_comment_list.html(data.comment_html);
                        $this.find('#id_icerik').val('');
                    },
                    error:function() {
                    alert("Bir hata oluştu.")
                    }
                    })

            })
            $window.on('click','#blog_comment_list div.row a.yanitla_button',function(e){
            e.preventDefault();
            var $this = $(this);
            var $parent = $this.closest('div');
            var $href = $this.attr('href');
            var $comment_pk = $this.attr('comment_pk');
            $.ajax({
            url : $href,
            type:"GET",
            dataType:'json',
            data:{comment_pk: $comment_pk},
            success:function(data){
                var $form_html = data.form_html;
                $parent.find('.child_form_container').html($form_html);
            },
            error:function(){
            }
            })
            })
        })
    </script>

    {% endblock %}
        {% block icerik %}
<div>    <div class="row">
    <div class="col-lg-12">

        <div class="col-lg-8 col-lg-offset-2">
            <h2 class="page-header"><a href="{% url 'posts:list' %}"><span class="glyphicon glyphicon-circle-arrow-left"></span></a><a href="#">{{blog.title |upper}}</a>
                  <span style="font-size: 20px">  {{blog.get_yayin_taslak_html }}
                  <a href="{% url 'posts:add_remove_favorite' blog.slug %}?next={% url 'posts:detail' blog.slug %}" class="btn btn-sm btn-default">
                           <span class="glyphicon glyphicon-star {% if request.user.username in blog.get_added_favorite_user %}active{% endif %}"></span>
                       </a></span>
                <small class="pull-right"><span class="glyphicon glyphicon-time"></span>{{blog.created_date}}</small></h2>
            {% if blog.get_image %}

            <div class="row">
                <div class="col-lg-12">
            <p><a href="{% url 'auths:user_profile' blog.user %}"><b><span class="glyphicon glyphicon-user"></span>Yazar {{blog.user.userprofile.get_screen_name}}</b></a></p>
                    <img class="img-responsive" src="{{blog.get_image}}">
                </div>
                </div>
            {% endif %}

            <div class="row">
                <div class="col-lg-12">
                    <p class="lead">
                {{blog.content |safe}}
            </p>

            <p class="lead">
                 Kategoriler: {{blog.kategoriler.all | join:","}}

            </p>
            </div>
                </div>
            {% if request.user == blog.user %}
            <div class="row">
                    <br>
           <div class="col-lg-3">
            <a class="btn btn-primary btn-sm" href="{% url 'posts:update' blog.slug %}">Güncelle</a>
            <a class="btn btn-danger btn-sm" href="{% url 'posts:delete' blog.slug %}">Sil</a>
          </div>
          </div>
            {% endif %}

        <div class="row">
            <h2 class="page-header">Yorumlar ({{blog.get_blog_comment_count}})</h2>
            <div class="col-lg-12" id="blog_comment_list">
                {% include 'blog/include/comment/comment_list_partial.html' with blog=blog %}
            </div>
        </div>
        <div class="row" style="margin-top: 50px;">
                <form class="comment_form" action="{% url 'posts:new_add_comment' blog.pk 'blog'  %}" method="post">
                    {% csrf_token  %}
                    {% for field in form %}
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="col-l-12">
                            <img style="height:75px;" class="img-circle" src="{{ request.user.userprofile.get_profile_photo }}">
                            </div></div>
                        <div class="col-lg-10">
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                                 {% if field.errors %}
            {% for error in field.errors %}
            <span class="text-danger"><b>{{error}}</b></span>
            {% endfor %}
            {% else %}
            {% if field.help_text %}
            <span class="text-success"><b>{{field.help_text}}</b></span>
            {% endif %}
            {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                    <input type="submit" value="Yorum Yap" class="pull-right btn btn-success">
                </div>
                </div>
                </div>
                </form>
            </div>
    </div>
</div>
    </div>
        {% endblock %}

templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block ust_icerik %}
    <script type="text/javascript" rel="script">
        $(document).ready(function (){
        $(".post").on('click', '.add_favorite_button',function (e){
        e.preventDefault();
        var $this = $(this);
        var $url = $this.attr('href');
        $.ajax({
        url:$url,
        method:"GET",
        data:{},
        success:function(data){
        var response = data.status;
        var $span = $this.find('span');
        var count = data.count;
        if(response === 'added')

            $span.addClass('active');

        else
        $span.removeClass('active');
        $this.closest('div').find('.post_favorite_count').html(count)
        }
        })
        }).on('click','.post_favorite_span',function(e){
        e.preventDefault();
        var $this = $(this);
        var $url = $this.attr('url');
        var $modal = $("#post_favorite_modal");
        var $baslik = $this.closest('div.post').find('h2 span').html();

        $.ajax({
        url:$url,
        method:"GET",
        dataType:'json',
        beforeSend:function(){
        $modal.modal('show');
        },
        success:function(data){
        $modal.find('.modal-body').html(data.html).append(data.page_html)
        $modal.find('.modal-title').html($baslik);
        }
        })
        });
        $("#post_favorite_modal").on('click','button.follow_button',function(e){
        e.preventDefault();
        var $this = $(this)
        var $row = $this.closest('div.row');
        var $url = $this.attr('url')
        var $followed_user = $this.attr('followed_username');
        var $follower_user = $this.attr('follower_username');
        var new_data = {'followed_username':$followed_user,'follower_username':$follower_user}

        $.ajax({
        url:$url,
        dataType:'json',
        method:"GET",
        data : new_data,
        success:function (data){
        $row.html(data.html);
        }
        })
        }).on('click','#favorite_paginate',function(e){
        e.preventDefault();
        var $this = $(this);
        var $this_parent = $this.closest('div');
        var $user_favorite_list = $this.closest('.modal-body').find('#user_favorite_list')
        var $url = $this.attr('href');
        $.ajax({
        url:$url,
        method:"GET",
        success:function(data){
            $user_favorite_list.append(data.html);
            $user_favorite_list.after(data.page_html);
            $this_parent.remove();

        }
        })
        })
        })
    </script>
    {% endblock %}
        {% block icerik %}
<div class="row">
    <div class="col-lg-12">
        {% include 'blog/include/favorite/favorite_modal.html' %}
        <div class="col-lg-8 col-lg-offset-2">
                            <div class="row">
                                <div class="col-lg-12">
                                <form class="form-inline" action="{% url 'posts:list' %}">
                                    {% for field in form %}
                                    <div class="form-group">
                                        {{field}}
                                        {% for error in field.errors %}
                                        <span class="text-danger"><b>{{error}}</b></span>
                                    {% endfor %}
                                    </div>
                                {% endfor %}


                                    <input class="btn btn-success" value="Sorgula" type="submit">
                                </form>
                        </div>
                        </div>
                    {% for post in posts.object_list %}
                        <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}"><span>{{post.title}}</span></a>
                    <small style ="font-size:small">
                       <span style="font-size: 20px"> {{post.get_yayin_taslak_html}}
                       <a href="{% url 'posts:add_remove_favorite' post.slug %}"
                          class="add_favorite_button btn btn-sm btn-default">
                           <span class="glyphicon glyphicon-star {% if request.user.username in post.get_added_favorite_user %}active{% endif %}"></span>
                       </a>
                       </span>
                        <span class="glyphicon glyphicon-time"></span>{{post.created_date}}</small>

                </h2>
            {% if post.get_image %}
            <img class="img-responsive" style="width:500px" src="{{post.get_image}}">
            {% endif %}
            <p><b><span class="glyphicon glyphicon-user"></span>
                Yazar <a href="{% url 'auths:user_profile' post.user.username %}">{{post.user.username}}</a></b>
                <br>
                <span title="Yorum Sayısı">
                <b class="post_comment_count">{{post.get_comment_count}}</b><span class="glyphicon glyphicon-comment"></span>
            -</span>
                <span url="{% url 'posts:post_list_favorite_user' post.slug %}" class="post_favorite_span"
                      title="Favorilere Eklenme Sayısı">
                <a href=""><b class="post_favorite_count">{{post.get_favorite_count}}</b><span
                        class="glyphicon glyphicon-star active"></span></a>
            </span>
            </p>

                    <p style="font-size:large; margin-top;20px">{{post.content|safe|linebreaksbr|truncatechars:50}} - </p>
                </div>
            {% empty %}
                    <p>Aradığınız kriterde bir blok bulunamadı.</p>
            {% endfor %}
        </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-8 col-lg-offset-2">
            {% if posts.has_other_pages %}
            <ul class="pagination">
            {% if posts.has_previous %}
                <li><a href="?page={{posts.previous_page_number}}{% if request.GET.taslak_yayin %}&taslak_yayin={{request.GET.taslak_yayin}}{% endif %}{% if request.GET.taslak_yayin %}&search={{request.GET.search}}{% endif %}"> &laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                <li class="active"><span> {{i}} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{i}}{% if request.GET.taslak_yayin %}&taslak_yayin={{request.GET.taslak_yayin}}{% endif %}{% if request.GET.taslak_yayin %}&search={{request.GET.search}}{% endif %}">{{i}}</a></li>
            {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                <li><a href="?page={{posts.next_page_number}}{% if request.GET.taslak_yayin %}&taslak_yayin={{request.GET.taslak_yayin}}{% endif %}{% if request.GET.taslak_yayin %}&search={{request.GET.search}}{% endif %}"> &raquo;</a></li>
                {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                {% endif %}

            </ul>
                {% endif %}
        </div>
        </div>
        </div>
    </div>
</div>
        {% endblock %}

templates/blog/post_update.html
{% extends "base.html" %}

{% block title %}
Post Update
{% endblock title %}

{% block icerik %}
div class="row" >
    <div class="col-lg-6 col-lg-offset-3">
        <h1 class="page-header">Post Update</h1>
    <form action="{% url 'posts:update' blog.slug %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% include 'blog/include/form-include.html' %}

    <div class="form-group">
        <div class="row">
            <div class="col-lg-12">
                <input type="submit" value="Güncelle" class="btn pull-right btn-sm btn-success">
            </div>
        </div>
    </div>
</form>
    </div>
    </div>

{% endblock icerik %}