auths/urls.py
from django.conf.urls import url
from .views import register,user_login
from django.urls import path,include
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from auths import views


app_name = "auths"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('settings/',views.user_settings,name = "settings"),
    path('user_profile/<str:username>/about/',views.user_about, name="about"),
    path('user_profile/<str:username>/',views.user_profile, name="user_profile"),
    path('password_change/',views.user_password_change,name ="password_change"),

]

blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib import admin
from django.utils.text import slugify

app_name = "posts"

urlpatterns = [
    path('/posts',views.posts,name = "posts"),
    path('',views.posts_list, name = "list"),
    path('update/<slug:slug>',views.post_update, name = "update"),
    path('create/',views.post_create, name = "create"),
    path('delete/<slug:slug>', views.post_delete, name = "delete"),
    path('krallar/<slug:slug>',views.krallar, name = "krallar"),
    path('detail/<slug:slug>',views.detail, name = "detail"),
    path('add_comment/<slug:slug>',views.add_comment, name = "add_comment"),
    path('get_child_comment_form/',views.get_child_form, name = "get_child_comment_form"),
    path('new_add_comment/<int:pk>/<str:model_type>',views.new_add_comment, name = "new_add_comment"),
    path('post_favorite_users/<slug:slug>',views.post_list_favorite_user, name = "post_list_favorite_user"),
    path('add_remove_favorite/<slug:slug>',views.add_or_remove_favorite, name = "add_remove_favorite"),


]

django_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include("blog.urls")),
    path('iletisim/',views.iletisim,name ="iletisim"),
    path('',views.anasayfa,name ="iletisim"),
    path('deneme/',views.deneme,name ="deneme"),
    path('deneme/ajax/',views.deneme_ajax,name ="deneme_ajax"),
    path('deneme/ajax_2/',views.deneme_ajax_2,name ="deneme_ajax_2"),
    path('auths/',include("auths.urls")),
    path('following/',include("following.urls")),
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        Title
        {% endblock %}</title>
    <link rel="stylesheet"  type="text/css " href="{% static 'Bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"  type="text/css " href="{% static 'Bootstrap/css/bootstrap-theme.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
  <script type="text/javascript" src="{% static 'Bootstrap/js/jquery.js' %}"rel="script"></script>

    <script type="text/javascript" rel="script" src="{% static 'Bootstrap/js/bootstrap.min.js' %}"></script>
    {% block ust_icerik %}

{% endblock %}
</head>
<body style="padding: 30px;">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'posts:list' %}">Django Blog Eğitim</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'posts:list' %}">Anasayfa <span class="sr-only">(current)</span></a></li>


          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <li><a href="{% url 'posts:create'  %}"><span class="glyphicon glyphicon-plus"></span>Post Create</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.userprofile.get_screen_name|upper}} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'auths:user_profile' request.user.username %}"><span class="glyphicon glyphicon-user"></span>Profile</a></li>
            <li><a href="{% url 'auths:settings' %}"><span class="glyphicon glyphicon-cog"></span>Settings</a></li>
            <li><a href="{% url 'auths:password_change' %}"><span class="glyphicon glyphicon-lock"></span>Password Change</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'auths:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container" style="margin-top: 30px;">
        {% include "messages.html" %}
    {% block icerik %}
e

{% endblock %}
</div>
</body>
</html>

templates/base_is_anonymous.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        Title
        {% endblock %}</title>
    <link rel="stylesheet"  type="text/css " href="{% static 'Bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet"  type="text/css " href="{% static 'Bootstrap/css/bootstrap-theme.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
  <script type="text/javascript" src="{% static 'Bootstrap/js/jquery.js' %}"rel="script"></script>

    <script type="text/javascript" rel="script" src="{% static 'Bootstrap/js/bootstrap.min.js' %}"></script>
    {% block ust_icerik %}
{% endblock %}
</head>
<body style="padding: 30px;">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Django Blog Eğitim</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

  </div><!-- /.container-fluid -->
</nav>


<div class="container" style="margin-top: 30px;">
        {% include "messages.html" %}
    {% block icerik %}
e

{% endblock %}
</div>
</body>
</html>

templates/deneme.html
{% extends 'base.html' %}
{% load static %}

{% block ust_icerik %}
<script type="text/javascript" rel="script">
    $(document).ready(function () {

        $("#ogrenci_getir").click(function (){
        $.ajax({
        type:'GET',
        url:"{% url 'deneme_ajax_2' %}",
        dataType:'json',
        data:{},
        success:function(data){
        $("#gelen_mesaj").html(data.html)
        }
        })

        });


        $("#ajax_deneme_form").submit(function(e){
        e.preventDefault();
        var $this = $(this);
        var type = $this.attr('method');
        var action = $this.attr('action');
        var data = $this.serialize()

        $.ajax({
        url:action,
        type:type,
        data:data,
        success:function(data){
        $this.append(data.isim)
        }
        })

        console.log(data);
        console.log(action);
        console.log(type);

        });

        $('#selam').click(function () {
            var $this = $(this);
            var url = $this.attr('url')
            $.ajax({
            url : url,
            method:"POST",
            dataType:'json',
            data:{'csrfmiddlewaretoken':'{{csrf_token}}'},
            success:function(data){
            $this.html(data.msg)
            }
            })

    })
      $('#merhaba').click(function(){
        var $this = $(this)
        var adres = $(this).attr('url');
        $.ajax({
         url:adres,
         type:"GET",
         dataType:'json',
         success: function(data){
            $this.html(data.msg)
         }
        })
    });

    $("a").click(function (e){
    e.preventDefault();
     var $this = $(this);
     var href = $(this).attr('href')
     console.log(href)
     //var username  = $this.attr('username','babacık');
     //username = $this.attr('username')
     //console.log(username)
    })
    })

</script>

{% endblock ust_icerik %}


{% block icerik %}
<div class="row" >
<div class="col-lg-6 pull-center">
    <button url="{% url 'deneme_ajax' %}" id="selam" name="selam" class="deneme btn btn-success">
        Selam
    </button>
        <button id="merhaba" url="{% url 'deneme' %}" name="merhaba" class="btn btn-danger">
            Merhaaabaaaa
        </button>
    <a href="{% url 'posts:list' %}" username="teoman" class="btn btn-primary">Tıklayın</a>

    <form method="post" id="ajax_deneme_form" action="{% url 'deneme_ajax' %}">
        {% csrf_token %}
        <input type="hidden" name="isim" value="ramazan">
        <button class="btn btn-success" type="submit">
            Ajax isteği gönder
        </button>
    </form>
</div>
    <div class="row">
        <div class="col-lg-6 pull-center">
            <h1>
                Render to String Kullanım
            </h1>
            <button class="btn btn-success" id="ogrenci_getir">
                Öğrenci Getir
            </button>
            <div id="gelen_mesaj">

            </div>
        </div>
    </div>
    </div>
{% endblock icerik %}

templates/iletisim.html
{% extends "base.html" %}

{% block title %}
İletişim
{% endblock %}


{% block icerik %}

<div class="col-lg-5 ">
   <h1 class="page-header">İletişim</h1>
   <form method="get" action="{% url 'iletisim' %}">
   {% for field in form %}
      <div class="form-group">
         <div class="row">
            <div class="col-lg-2 col-md-2">
                  <label for="{{field.id_for_label}}" class="control-label">{{field.label}}</label>
            </div>
               <div class="col-lg-10 col-md-10">
                  {{field}}
                  {% if field.errors %}
                  {% for error in field.errors %}
                  <span class="text-danger"><br><b>{{error}}</b></span>
                  {% endfor %}
                  {% endif %}
               </div>

         </div>
      </div>
    {% endfor %}
      <input type="submit" class="btn btn-sm btn-success">
   </form>
</div>
<div class="col-lg-5">
   <h1 class="page-header">Mesajlar</h1>
{% for mesaj in mesajlar%}
   <div class="form-group">
      <p class="lead">{{forloop.counter}}{{mesaj.isim}} {{mesaj.soyisim}} {{mesaj.email}} {{mesaj.icerik}}</p>
   </div>
   {% empty %}
   <p class="lead"> <span class="glyphicon glyphicon-inbox"></span>Henüz bir mesaj bulunamadı.</p>

   {% endfor %}

</div>

{% endblock icerik %}

templates/messages.html
{% if messages %}

  <div class="row">
            <div class="col-lg-8" style="float:none;margin:0 auto;margin-top:50px;">
                {% for message in messages %}

                {% if message.tag == "info" %}
                <div class=" alert alert-dismissible alert-danger">{{ message |safe }}
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>


                {% else %}
                <div class=" alert alert-dismissible alert-{{ message.tags }}">{{ message | safe}}
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>
                {% endif %}

                </div>
                </div>
                {% endfor %}

                {% endif %}

templates/ogrenci_velisine_mesaj.html
<h1>
    Merhaba Sevgili Veli
</h1>
<p>
    Öğrencimiz {{ogrenci.isim_soyisim}} derslerinde bu aralar başarılı değil.
    Bunun nedenini size de sormak istedik.
</p>

<p>
    {{ogrenci.ogretmen_isim_soyisim}}
</p>