auths/urls.py
from django.conf.urls import url
from .views import register,user_login
from django.urls import path,include
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from auths import views


app_name = "auths"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('settings/',views.user_settings,name = "settings"),
    path('user_profile/<str:username>/about/',views.user_about, name="about"),
    path('user_profile/<str:username>/',views.user_profile, name="user_profile"),
    path('password_change/',views.user_password_change,name ="password_change"),

]

blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib import admin
from django.utils.text import slugify

app_name = "posts"

urlpatterns = [
    path('/posts',views.posts,name = "posts"),
    path('',views.posts_list, name = "list"),
    path('update/<slug:slug>',views.post_update, name = "update"),
    path('create/',views.post_create, name = "create"),
    path('delete/<slug:slug>', views.post_delete, name = "delete"),
    path('krallar/<slug:slug>',views.krallar, name = "krallar"),
    path('detail/<slug:slug>',views.detail, name = "detail"),
    path('add_comment/<slug:slug>',views.add_comment, name = "add_comment"),
    path('get_child_comment_form/',views.get_child_form, name = "get_child_comment_form"),
    path('new_add_comment/<int:pk>/<str:model_type>',views.new_add_comment, name = "new_add_comment"),
    path('post_favorite_users/<slug:slug>',views.post_list_favorite_user, name = "post_list_favorite_user"),
    path('add_remove_favorite/<slug:slug>',views.add_or_remove_favorite, name = "add_remove_favorite"),


]

django_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include("blog.urls")),
    path('iletisim/',views.iletisim,name ="iletisim"),
    path('',views.anasayfa,name ="iletisim"),
    path('deneme/',views.deneme,name ="deneme"),
    path('deneme/ajax/',views.deneme_ajax,name ="deneme_ajax"),
    path('deneme/ajax_2/',views.deneme_ajax_2,name ="deneme_ajax_2"),
    path('auths/',include("auths.urls")),
    path('following/',include("following.urls")),
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

following/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib import admin

app_name = "following"


urlpatterns = [
        path('takiplesme_sistemi/',views.kullanici_takip_et_cikar,name="kullanici_takip_et_cikar"),
        path('post_fav_user_takip_et_cikar/',views.kullanici_takip_et_cikar_for_post,name="post_fav_user_takip_et_cikar"),
        path('modal_takip_et_cikar/',views.kullanici_modal_takip_et_cikar,name="modal_takip_et_cikar"),
        path('ramo/', views.ramo, name = "ramo"),
        path('followed_or_followers_list/<str:follow_type>/', views.followed_or_followers_list, name = "followed_or_followers_list"),

]

auths/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db.models.signals import post_save

class UserProfile(models.Model):
    SEX = ((None,'Cinsiyet Seçiniz'),('diger','DİĞER'),('erkek','ERKEK'),('kadın','KADIN'))
    user = models.OneToOneField(User, null = True, blank = False, verbose_name = "User", on_delete = models.PROTECT)
    bio = models.TextField(max_length = 1000, verbose_name = "Hakkımda", blank = True, null = True)
    profile_photo = models.ImageField(null = True, blank = True, verbose_name = "Profil Fotoğrafı")
    dogum_tarihi = models.DateField(null = True, blank = True, verbose_name = "Dogum Tarihi" )
    sex = models.CharField(choices = SEX, blank = True, null = True, max_length = 6, verbose_name = "Cinsiyet")

    class Meta:
        verbose_name_plural = "Kullanici Profilleri"

    def get_screen_name(self):
        user = self.user
        user
        if user.get_full_name():
            return user.get_full_name()
        return user.username ##fullname almıyor. Fonksiyon işe yaramıyor.

    def user_full_name(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        return None



    def get_user_profile_url(self):
        url = reverse('auths:user_profile',kwargs = {"username": self.user.username})
        return url

    def get_profile_photo(self):
        if self.profile_photo:
            return self.profile_photo.url
        return "/static/img/profil_fotosu.jpg"

    def __str__(self):
        return "%s Profile" % (self.user)

def create_profile(sender,created,instance,**kwargs):
    if created:
        UserProfile.objects.create(user = instance)

post_save.connect(create_profile, sender = User)

auths/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordChangeForm
import re

from .models import UserProfile

class RegisterForm(forms.ModelForm):
    password = forms.CharField(min_length = 5, required = True, label = "Password", widget = forms.PasswordInput(attrs = {'class' : 'form-control'}))
    password_confirm = forms.CharField(min_length = 5, required = True, label = "Password Doğrula", widget = forms.PasswordInput(attrs = {'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ["first_name","last_name","username","email","password","password_confirm"]

    def __init__(self,*args,**kwargs):
        super(RegisterForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True


    def clean(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password != password_confirm:
            self.add_error("password","Parolalar Eşleşmedi.")
            self.add_error("password_confirm","Parolalar Eşleşmedi.")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        email = email.lower()
        if User.objects.filter(email = email).exists():
            raise forms.ValidationError("Bu Email Sistemde Kayıtlı.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(username = username).exists():
            raise forms.ValidationError("Bu kullanıcı adı sistemde mevcuttur.")
        return username

class LoginForm(forms.Form):
    username = forms.CharField(required = True, max_length = 50, label = "Username", widget = forms.TextInput(attrs = {"class": "form-control"}) )
    password = forms.CharField(required = True, max_length = 50, label = "Password",
                               widget = forms.PasswordInput(attrs = {"class": "form-control"}) )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username = username, password = password)
        if not user:
            raise forms.ValidationError("<b>Hatalı Kullanıcı Adı Veya Şifre Girdiniz</b>")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if re.match(r"[^@]+@[^@]+\.[^@]+",username):
            print("selamm")
            users = User.objects.filter(email__iexact = username)
            if len(users)>0 and len(users) ==1:
                return users.first().username
        return username

class UserProfileUpdateForm(forms.ModelForm):
    sex = forms.ChoiceField(required = True, choices = UserProfile.SEX)
    profile_photo = forms.ImageField(required = False)
    bio = forms.CharField(widget = forms.Textarea, required = False)
    dogum_tarihi = forms.DateField(input_formats = ("%d.%m.%Y",), widget = forms.DateInput(format = "%d.%m.%Y"), required = True, label = "Dogum Tarihi")

    class Meta:
        model = User
        fields = ["first_name","last_name","username","email","sex","profile_photo","bio"]

    def __init__(self,*args,**kwargs):
        super(UserProfileUpdateForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}
        self.fields['bio'].widget.attrs['rows'] = 10
        DATEPICKER = {
            'type':'text',
            'class':'form-control',
            'autocomplete':'off'
        }
        self.fields['dogum_tarihi'].widget.attrs.update({"id": "datetimepicker1"})

    def clean_email(self):
        email = self.cleaned_data.get("email",None)
        #eger hic email adresi girilmemişse
        if not email:
            raise forms.ValidationError("Lütfen Email Bilgisi Giriniz.")
        if User.objects.filter(email = email).exclude(username = self.instance.username).exists():
            raise forms.ValidationError("Bu email adresi sistemde kayıtlı.")
        return email

class UserPasswordChangeForm(forms.Form):
    user = None
    old_password = forms.CharField(min_length = 4, required = True, label = "Mevcut Şifreniz", widget = forms.PasswordInput(attrs = {"class": "form-control"}))
    new_password = forms.CharField(min_length = 4, required = True, label = "Yeni Şifreniz", widget = forms.PasswordInput(attrs = {"class": "form-control"}))
    new_password_confirm = forms.CharField(min_length = 4, required = True, label ="Yeni Şifre Doğrulama", widget = forms.PasswordInput(attrs = {"class": "form-control"}))

    def __init__(self,user,*args,**kwargs):
        print(user)
        self.user = user
        super(UserPasswordChangeForm,self).__init__(*args,**kwargs)

    def clean(self):
        new_password = self.cleaned_data.get('new_password')
        new_password_confirm = self.cleaned_data.get('new_password_confirm')

        if new_password != new_password_confirm:
            self.add_error("new_password","Şifreler Eşleşmedi")
            self.add_error("new_password_confirm","Şifreler Eşleşmedi")

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if not self.user.check_password(old_password):
            raise forms.ValidationError("Lütfen Şifrenizi Giriniz.")
        return old_password


class UserPasswordChangeForm2(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(user, *args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}

auths/views.py
from django.shortcuts import render,reverse,HttpResponseRedirect,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm,LoginForm,UserProfileUpdateForm,UserPasswordChangeForm2
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from following.models import Following

from django.contrib.auth.decorators import login_required
from blog.decorators import anonymous_required
from .models import UserProfile
from blog.models import Blog

# Create your views here.

@anonymous_required
def register(request):
    if not request.user.is_anonymous:
        return HttpResponseRedirect(reverse("posts:list"))
    #if request.user.is_authenticated:
    #   return HttpResponseRedirect(reverse("post:list"))

    form = RegisterForm(data = request.POST or None)
    if form.is_valid():
        user = form.save(commit = False)
        password = form.cleaned_data.get("password")
        username = form.cleaned_data.get("username")
        user.set_password(password)
        user.save()
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request,user)
                messages.success(request,"<b>Tebrikler kaydınız başarıyla gerçekleşti.</b>",extra_tags = "success")
                return HttpResponseRedirect(user.userprofile.get_user_profile_url())
    return  render(request, 'auths/register.html', context = {"form":form})

@anonymous_required
def user_login(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                msg = "<b>Merhaba %s Sisteme Hoşgeldiniz.</b>"%(username)
                messages.success(request,msg , extra_tags="success")
                return HttpResponseRedirect(reverse("posts:list"))
    return render(request,"auths/login.html" ,context = {"form": form})


def user_logout(request):
    username = request.user.username
    logout(request)
    msg = "<b>Sistemden Çıkış Yaptınız {}  </b>".format(username)
    messages.success(request,msg,extra_tags = "success")
    return HttpResponseRedirect(reverse("auths:login"))

def user_profile(request,username):
    takip_ediyor_mu = False
    user = get_object_or_404(User, username = username)
    blog_list = Blog.objects.filter(user = user)
    takipci_ve_takip_edilen = Following.kullanici_takiplesme_tablosu(user)
    takipciler = takipci_ve_takip_edilen['takipciler']
    takip_edilenler = takipci_ve_takip_edilen['takip_edilenler']

    #eğer kendi profiline girmişse fonksiyon gereksiz çalışmasın diye
    if user != request.user:
        takip_ediyor_mu = Following.kullanici_takip_kontrol(follower = request.user, followed = user)
    return render(request,"auths/profile/userprofile.html",
                  context = {'takipciler':takipciler, 'takip_edilenler':takip_edilenler, "takip_ediyor_mu":takip_ediyor_mu, "user": user, "blog_list":blog_list, 'page': 'user_profile'})

def user_settings(request):
    sex = request.user.userprofile.sex
    bio = request.user.userprofile.bio
    profile_photo = request.user.userprofile.profile_photo
    dogum_tarihi = request.user.userprofile.dogum_tarihi

    takipci_ve_takip_edilen = Following.kullanici_takiplesme_tablosu(request.user)
    takipciler = takipci_ve_takip_edilen['takipciler']
    takip_edilenler = takipci_ve_takip_edilen['takip_edilenler']

    initial = {'sex' : sex, 'bio' : bio, 'profile_photo' : profile_photo, "dogum_tarihi": dogum_tarihi}
    form = UserProfileUpdateForm(initial = initial, instance = request.user, data = request.POST or None, files = request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save(commit = True)
            bio = form.cleaned_data.get('bio',None)
            sex = form.cleaned_data.get('sex',None)
            dogum_tarihi = form.cleaned_data.get("dogum_tarihi",None)
            profile_photo = form.cleaned_data.get('profile_photo',None)

            user.userprofile.bio = bio
            user.userprofile.sex = sex
            user.userprofile.dogum_tarihi = dogum_tarihi
            user.userprofile.profile_photo = profile_photo
            user.userprofile.save()
            messages.success(request,"Tebrikler Kullanıcı Bilgileriniz Başarıyla Güncellendi.",extra_tags = "success")
            return HttpResponseRedirect(reverse('auths:user_profile', kwargs = {'username': user.username}))
        else:
            messages.warning(request,"Lütfen Form Alanlarına Doğru Giriniz.",extra_tags = "danger")
    return render(request, "auths/profile/settings.html", context={'takipciler':takipciler,
                                            'takip_edilenler':takip_edilenler, "form": form, 'page': 'settings'})

def user_password_change(request):
    form = UserPasswordChangeForm2(user = request.user, data = request.POST or None)
    takipci_ve_takip_edilen = Following.kullanici_takiplesme_tablosu(request.user)
    takipciler = takipci_ve_takip_edilen['takipciler']
    takip_edilenler = takipci_ve_takip_edilen['takip_edilenler']

    if form.is_valid():
        user = form.save(commit = True)
        update_session_auth_hash(request, user)
        messages.success(request,"Tebrikler Şifreniz Başarıyla Güncellendi.")
        return HttpResponseRedirect(reverse('auths:user_profile',kwargs = {"username": request.user.username}))
    return render(request,"auths/profile/password_change.html", context = {'takipciler':takipciler,
                                            'takip_edilenler':takip_edilenler,"form": form, 'page': 'password_change'})

def user_about(request,username):
    takip_ediyor_mu = False
    user = get_object_or_404(User, username = username)
    takipci_ve_takip_edilen = Following.kullanici_takiplesme_tablosu(user)
    takipciler = takipci_ve_takip_edilen['takipciler']
    takip_edilenler = takipci_ve_takip_edilen['takip_edilenler']

    # eğer kendi profiline girmişse fonksiyon gereksiz çalışmasın diye
    if user != request.user:
        takip_ediyor_mu = Following.kullanici_takip_kontrol(follower=request.user, followed=user)

    return render(request,"auths/profile/about_me.html",
                  context = {'takipciler':takipciler, 'takip_edilenler':takip_edilenler,
                                                 "takip_ediyor_mu":takip_ediyor_mu, "user": user, "page":"about"})

templates/auths/profile/about_me.html
{% extends "auths/profile/user_profile_base.html" %}
{% block profil_icerik %}
<div class="caption">

    {{user.userprofile.bio|linebreaksbr}}
</div>

{% endblock profil_icerik %}

templates/auths/profile/password_change.html
{% extends "auths/profile/user_profile_base.html" %}
{% block profil_icerik %}

<div class="row" style="margin-top:20px;">
<div class="col-lg-10 pull-center">
    <form method="post" action="{% url 'auths:password_change' %}">
        {% csrf_token %}
        {% for field in form %}
    <div class="form-group">
    <label class="control-label">{{field.label}}</label>
    {{field}}
        {% if field.errors %}
            {% for error in field.errors %}
            <span class="text-danger"><b>{{error}}</b></span>
            {% endfor %}
            {% else %}
            {% if field.help_text %}
            <span class="text-success"><b>{{field.help_text}}</b></span>
            {% endif %}
            {% endif %}
        </div>
    {% endfor %}
<div class="form-group">
    <input type="submit" value="Şifre Değiştir" class="pull-right btn btn-sm btn-success">
</div>

    </form>
</div>
</div>

{% endblock profil_icerik %}

templates/auths/profile/settings.html
{% extends "auths/profile/user_profile_base.html" %}
{% load static %}

{% block ust_icerik %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<link type="text/css" rel="stylesheet" href="{% static 'bootstrap-datetime/bootstrap-datetime.css' %}">
<script type="text/javascript" src="{% static 'bootstrap-datetime/bootstrap-datetime.js'%}" rel="script"></script>
<script>
    $(document).ready(function () {
    $('#datetimepicker1').datetimepicker({
    format:"DD.MM.YYYY"
    });
    })

</script>

{% endblock ust_icerik %}


{% block profil_icerik %}
<div class="row">
<div class="col-lg-10 pull-center">
    <form method="post" enctype="mu ltipart/form-data" action="{% url 'auths:settings' %}">
            {% csrf_token %}
    {% for field in form %}
    {% if field.name == 'dogum_tarihi' %}
            <div class="form-group">
                <label class="control-label">{{field.label}}</label>
                <div class='input-group date' id='datetimepicker1'>
                    {{field}}
                    {% if field.errors %}
            {% for error in field.errors %}
            <span class="text-danger"><b>{{error}}</b></span>
            {% endfor %}
            {% else %}
            {% if field.help_text %}
            <span class="text-success"><b>{{field.help_text}}</b></span>
            {% endif %}
            {% endif %}

                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </div>

    {% else %}
    <div class="form-group">
    <label class="control-label">{{field.label}}</label>
    {{field}}
        {% if field.errors %}
            {% for error in field.errors %}
            <span class="text-danger"><b>{{error}}</b></span>
            {% endfor %}
            {% else %}
            {% if field.help_text %}
            <span class="text-success"><b>{{field.help_text}}</b></span>
            {% endif %}
            {% endif %}
        </div>
        {% endif %}

    {% endfor %}
    <div class="form-group pull-right">
        <input type="submit" value="Kaydet" class="btn btn-sm btn-success">
    </div>
        </form>

</div>
    </div>
{% endblock profil_icerik %}

templates/auths/profile/user_profile_base.html
{% extends "base.html" %}
{% load static %}

{% block ust_icerik %}

<style rel="stylesheet" type="text/css">
    .modal-dialog {
        overflow-y:hidden;
    }

    .modal-body{
    height: 250px;
    overflow-y: auto;
    }
</style>

    <script type="text/javascript" rel="script">
    $(document).ready(function () {
        $("#user_following").on('click','.follow_button',function (){
        var $this = $(this);
        var $url = $this.attr('url');
        var $username = $this.attr('username')
        var $follow_type = $this.attr("follow_type");
        var $modal = $("#profile_following_modal");
        $modal.attr('follow_type', $follow_type);
        if($follow_type ==="followed")
        $modal.find('.modal-title').html("Takip Edilenler");
        else if($follow_type === "followers"){
        $modal.find(".modal-title").html("Takipçiler");
        }

        //ajax request başlangıç
        $.ajax({
        url : $url,
        method:"GET",
        dataType:'json',
        data: {'username':$username},
        success: function(data){
            $modal.find('#follow_paginate').closest('div').remove();
            $modal.find('.modal-body #follow_list').html('').prepend(data.html).after(data.html_paginate);
            $modal.modal('show');
        }

        })

        })
        $("#takip_et_cikar_button").click(function () {

    var $this = $(this);
    var $url = $this.attr('url');
    var $takip_eden = $this.attr('takip_eden');
    var $takip_edilen = $this.attr('takip_edilen');

    var data = {follower_username:$takip_eden, followed_username:$takip_edilen};

    $.ajax({
    url : $url,
    type: 'GET',
    dataType: 'json',
    data:data,
    success:function (data){
    if (data.is_valid){
    $this.html(data.msg)
    $("#user_following").html(data.html)
     }
    }
  })
 })
$("#profile_following_modal").on('click','#follow_list .follow .follow_button',function (e){
var $this = $(this);
var $modal_body = $this.closest('.modal-body');
var $modal = $($this.closest('.modal'))
var $follow_type = $modal.attr('follow_type');
var $owner = $modal.attr('owner');
var $span = $($this.closest('.follow').find('span'));
var takip_edilen = $span.attr('takip_edilen')
var takip_eden = $span.attr('takip_eden')
var url = "{% url 'following:modal_takip_et_cikar' %}"
var data = {owner: $owner, follow_type: $follow_type, follower_username: takip_eden, followed_username: takip_edilen};

$.ajax({
url :url,
type:"GET",
dataType:"json",
data:data,
success: function (data){

if (data.owner){
if(data.follow_type === 'followed')
{
var $follow_list = $modal_body.find("#follow_list");
$follow_list.html(data.html);
$modal_body.find("#follow_paginate").closest('.row').remove();
$follow_list.after(data.html_paginate)
}
else
{
if(data.takip_durum){
$this.removeClass('btn-success');
$this.addClass('btn-danger');
}
else{
$this.removeClass('btn-danger');
$this.addClass('btn-success');
}
$this.html(data.msg);

}
$("#user_following").html(data.html_render_takip_durum)
}
else{
if(data.takip_durum){
$this.removeClass('btn-success');
$this.addClass('btn-danger');
}
else{
$this.removeClass('btn-danger');
$this.addClass('btn-success');
}
$this.html(data.msg);
}
}
})
}).on('click',"#follow_paginate",function (e){
e.preventDefault();
var $this = $(this);
var $follow_list = $this.closest('.modal').find('#follow_list');
var $follow_paginate = $this.closest('.modal').find('#follow_paginate');
var url = $this.attr('href');

$.ajax({
url: url,
dataType:'json',
method: "GET",
beforeSend: function(){
var $img = $('<img class="img-responsive" src="{% static 'img/ajax-loader.gif' %}" />')
$follow_paginate.html($img);
},
success:function (data){
if( data.is_valid ){
$follow_list.append(data.html);
$follow_paginate.remove();
$follow_list.after(data.html_paginate)
}
}
})
})
})
    </script>
{% endblock %}

{% csrf_token %}
{% block title %}
{{user.profile.get_screen_name}}
{% endblock title %}

{% block icerik %}
<div class="row" id="follow_list">
    <div class="col-lg-10 user-profile pull-center">
        {% include 'following/profile/include/following_modal.html' %}
        {% if request.user != user %}
        <div>
    <button takip_edilen="{{user.username}}" takip_eden="{{request.user.username}}" url="{% url 'following:kullanici_takip_et_cikar' %}" id="takip_et_cikar_button" class="btn btn-success btn-md">
        {% if takip_ediyor_mu == True %}
        <b>Takibi Bırak</b>
        {% else %}
        <b>Takip Et</b>
        {% endif %}
    </button>
</div>
        {% endif %}
        <div class="text-center">
          <img class="img-circle user-profile-img" style="width:90px"  src="{{user.userprofile.get_profile_photo}}">
</div>
        <div class="text-center">
            <br>
            {% if user.userprofile.user_full_name %}
        <span class="text"><b> {{user.userprofile.user_full_name|upper}} </b></span>
            <br>
            {% endif %}
        <span class="text">
            <b>
                @{{user.username}}
            </b>
        </span>
    <span class="text">
        <br>
        <b>
                {{user.userprofile.get_sex_display}}
            </b>
        </span>

        </div>
        <div id="user_following" class="row">
            {% include 'auths/profile/include/following/following_partion.html' %}
        </div>

        {% if request.user == user %}

        {% include 'auths/profile/include/owner_navbar.html' %}
        {% else %}
        {% include 'auths/profile/include/visitor_navbar.html' %}

        {% endif %}
        <div>
            {% block profil_icerik %}

            {% endblock profil_icerik %}
        </div>
    </div>
</div>


{% endblock icerik %}

templates/auths/profile/userprofile.html
{% extends 'auths/profile/user_profile_base.html' %}
{% load static %}
{% block profil_icerik %}

<div class="row">
    <div class="col-lg-12">
        {% for post in user.blog.all%}
        <div class="row" style="margin-top: 20px;">
            <div class="col-lg-10 pull-center">
                <h1><a href="{% url 'posts:detail' post.slug %}">{{post.title}}</a>
                <small>
                    {{post.get_yayin_taslak_html}}
                </small>
                    <small class="pull-right">
                    <span class="glyphicon glyphicon-time"></span>
                    <span>{{post.created_date}}</span>
                </small>
                </h1>

                <img src="{{post.get_image}}" class="img-responsive">
                <p>{{post.content|safe|truncatewords:30}}</p>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock profil_icerik %}