auths/urls.py
from django.conf.urls import url
from .views import register,user_login
from django.urls import path,include
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from auths import views


app_name = "auths"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.user_login,name = "login"),
    path('logout/',views.user_logout,name = "logout"),
    path('settings/',views.user_settings,name = "settings"),
    path('user_profile/<str:username>/about/',views.user_about, name="about"),
    path('user_profile/<str:username>/',views.user_profile, name="user_profile"),
    path('password_change/',views.user_password_change,name ="password_change"),

]

blog/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib import admin
from django.utils.text import slugify

app_name = "posts"

urlpatterns = [
    path('/posts',views.posts,name = "posts"),
    path('',views.posts_list, name = "list"),
    path('update/<slug:slug>',views.post_update, name = "update"),
    path('create/',views.post_create, name = "create"),
    path('delete/<slug:slug>', views.post_delete, name = "delete"),
    path('krallar/<slug:slug>',views.krallar, name = "krallar"),
    path('detail/<slug:slug>',views.detail, name = "detail"),
    path('add_comment/<slug:slug>',views.add_comment, name = "add_comment"),
    path('get_child_comment_form/',views.get_child_form, name = "get_child_comment_form"),
    path('new_add_comment/<int:pk>/<str:model_type>',views.new_add_comment, name = "new_add_comment"),
    path('post_favorite_users/<slug:slug>',views.post_list_favorite_user, name = "post_list_favorite_user"),
    path('add_remove_favorite/<slug:slug>',views.add_or_remove_favorite, name = "add_remove_favorite"),


]

django_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include("blog.urls")),
    path('iletisim/',views.iletisim,name ="iletisim"),
    path('',views.anasayfa,name ="iletisim"),
    path('deneme/',views.deneme,name ="deneme"),
    path('deneme/ajax/',views.deneme_ajax,name ="deneme_ajax"),
    path('deneme/ajax_2/',views.deneme_ajax_2,name ="deneme_ajax_2"),
    path('auths/',include("auths.urls")),
    path('following/',include("following.urls")),
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/auths/profile/include/both_navbar_fields.html
 <li role="presentation" class="{% if page == 'user_profile' %}active{% endif %}"><a href="{% url 'auths:user_profile' user.username %}">Gönderiler</a></li>
 <li role="presentation" class="{% if page == 'about' %}active{% endif %}"><a href="{% url 'auths:about' user.username %}">Hakkımda</a></li>

templates/auths/profile/include/owner_navbar.html
<ul class="nav nav-pills">

    {% include 'auths/profile/include/both_navbar_fields.html' %}
    <li role="presentation" class="{% if page == 'settings' %}active{% endif %}"><a href="{% url 'auths:settings'  %}">Ayarlar</a></li>
            <li role="presentation" class="{% if page == 'password_change' %}active{% endif %}"><a href="{% url 'auths:password_change'  %}">Password Change</a></li>
        </ul>

templates/auths/profile/include/visitor_navbar.html
<ul class="nav nav-pills">

{% include 'auths/profile/include/both_navbar_fields.html' %}

</ul>